name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow only on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK (Java 17)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'  # Use Java 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          target: android-33
          build-tools: 33.0.2

      - name: Cache Gradle files
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./src/gradlew  # Adjusted path to gradlew inside src folder

      - name: Run Android Lint
        run: ./src/gradlew --project-dir ./src/app lint  # Adjusted to include :app:lint for the specific app module

      - name: Upload Lint Results as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: lint-report
          path: ./src/app/build/reports/lint-results.html  # Path to lint results inside the app module

      - name: Deploy to Application Server
        if: github.ref == 'refs/heads/main'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > /tmp/serverkey.pem
          chmod 600 /tmp/serverkey.pem
          rsync --progress -r -e "ssh -v -o StrictHostKeyChecking=no -i /tmp/serverkey.pem" \
          ./src/PHP_Files/* \
          ubuntu@107.20.40.0:/var/www/html/backend/PHP_Files
