name: Build Android Staging App
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Android Staging App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history and tags

      - name: Debug Git Tags
        run: |
          git fetch --tags
          echo "List of all tags:"
          git tag --list
          echo "Latest tag detected:"
          git describe --tags --abbrev=0

      - name: Determine Versioning Components
        id: version
        run: |
          # Get the latest tag using Fastlane's logic
          LATEST_TAG=$(git tag --sort=-v:refname | head -n 1 || echo "v0.0")

          # Get the latest commit hash
          COMMIT_HASH=$(git rev-parse --short HEAD)

          # Get commit count since the latest tag
          if [ "$LATEST_TAG" = "v0.0" ]; then
            PATCH_VERSION=$(git rev-list --count HEAD)
          else
            PATCH_VERSION=$(git log --oneline ${LATEST_TAG}..${COMMIT_HASH} | wc -l | tr -d ' ')
          fi

          # Get the branch name and clean it
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/[^a-zA-Z0-9]/-/g')

          # Construct the version
          VERSION="${LATEST_TAG}.${PATCH_VERSION}.${BRANCH_NAME}.${COMMIT_HASH}"

          # Export the environment variables
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV
          echo "PATCH_VERSION=${PATCH_VERSION}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          echo "COMMIT_HASH=${COMMIT_HASH}" >> $GITHUB_ENV

      - name: Display Generated Version
        run: echo "Generated Version:${{ env.VERSION }}"
