name: Build Android Staging App
on:
  push:
    branches:
      - quality-gates-integeration
      - candidate
      - release
      - main
jobs:
  build:
    name: Build Android Staging App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Determine Versioning Components
        id: version
        run: |
          # Get the latest tag (sorted by version)
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          # Count commits since the latest tag
          if [ "$LATEST_TAG" = "v0.0.0" ]; then
            PATCH_VERSION=$(git rev-list --count HEAD)
          else
            PATCH_VERSION=$(git rev-list ${LATEST_TAG}..HEAD --count || echo 0)
          fi
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///' | sed 's/[^a-zA-Z0-9]/-/g')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          VERSION="${LATEST_TAG}.${PATCH_VERSION}.${BRANCH_NAME}.${COMMIT_HASH}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Install Bundler and Fastlane
        run: |
          export GEM_HOME=$HOME/.gem  # Set GEM_HOME to ~/.gem
          export GEM_PATH=$HOME/.gem  # Ensure GEM_PATH is set to the same directory
          export PATH=$HOME/.gem/ruby/3.2.0/bin:$PATH  # Add Ruby gems bin to PATH
          
          # Install bundler and fastlane
          gem install bundler -v 1.17.2 --user-install  # Install bundler
          gem install fastlane --user-install  # Install fastlane
          
          # Check if bundler is installed correctly
          echo "Bundler version: $(bundle -v)"

          # Install dependencies from Gemfile (if you have one)
          bundle install  
          
          # Run Fastlane with the specified lane
          bundle exec fastlane get_commits_count

