name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger workflow only on pushes to the main branch

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK 17 (Required for SonarQube)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Get Commit Details
        id: commit_details
        run: |
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
          echo "AUTHOR_EMAIL=$(git log -1 --pretty=%ce)" >> $GITHUB_ENV
        shell: bash

      - name: Print Commit Details
        run: |
          echo "Commit Message: ${{ env.COMMIT_MESSAGE }}"
          echo "Author Email: ${{ env.AUTHOR_EMAIL }}"

      - name: SonarQube Code Analysis
        env:
          SONAR_HOST_URL: "http://18.212.165.56:9000/"  # Replace with your EC2 SonarQube IP
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        run: |
          curl -o sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli.zip
          sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
          echo "export PATH=$PATH:/opt/sonar-scanner/bin" >> ~/.bashrc
          source ~/.bashrc
          
          sonar-scanner \
            -Dsonar.projectKey=Hotel-Reservation-App \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.php.coverage.reportPaths=coverage.xml

      - name: Deploy to Application Server
        if: github.ref == 'refs/heads/main'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > /tmp/serverkey.pem
          chmod 600 /tmp/serverkey.pem
          rsync --progress -r -e "ssh -v -o StrictHostKeyChecking=no -i /tmp/serverkey.pem" \
          ./src/PHP_Files/* \
          ubuntu@34.238.232.63:/var/www/html/backend/PHP_Files
